#!/usr/bin/with-contenv bash

[[ ! -d "/app/couchpotato/.git" ]] && \
git clone https://github.com/CouchPotato/CouchPotatoServer /app/couchpotato


mkdir -p /var/log/couchpotato
chown -R abc:abc /app
chmod 777 /var/log/couchpotato


# opt out for autoupdates
[ "$ADVANCED_DISABLEUPDATES" ] && exit 0

cd /app/couchpotato
git pull
chown -R abc:abc /app

