#!/usr/bin/with-contenv bash

echo '
******************************************************
******************************************************
*                                                    *
*                                                    *
*             This image is deprecated.              *
*      We will not offer support for this image      *
*             and it will not be updated.            *
*                                                    *
*                                                    *
******************************************************
******************************************************

This project is no longer maintained upstream and we will no longer be updating this image.
For an alternative try:
https://github.com/linuxserver/docker-radarr


******************************************************
******************************************************'
